### ISSUE TITLE
Basic Magento 2 Composition

### ISSUE THREAD

**Issue by evghen1** [web-seven/configuration-magento2-gcp#3]
## Issue summary:
As start of Magneto Crossplane configuration proposed to make Composition MVP which could be used for start minimal services for running Magento 2 in GKE.
## Issue details:
To make Magento 2 run in GKE we need to create Crossplane Composition with next services combined together:
- Public IP address.
- GKE Cluster.
- Ingress Controller
- Node Pool with configurable machine type.
- Magento 2 Helm chart from Bitnami.
- Managed MySQL Database from GCP (not in GKE).
## Todo:
- [x] Create Composition with all service from details.
- [x] Create XRD Magento2 and assign it to Composition.
- [x] Define Crossplane configuration package.
- [x] Make Github Action for packaging and publish Configuration to Web7 packages repository: ghcr.io/web-seven/configuration-magento2-gcp
## Acceptance criteria:
- User shall be able to install configuration into KNDP environment and by creation of Magento2 CRD create basic Magento installation in GKE.

**Comment by evghen1** [comment]
@ca7alindev Any news?

**Comment by ca7alindev** [comment]
@evghen1 I am having some problems connecting cluster with sql database, and now just figured out how to resolve using private ip from same network, almost done

**Comment by evghen1** [comment]
@ca7alindev Please mark which steps was done in issue description
